version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  app:
    restart: always
    build: .
    ports:
      - 5000:5000